[build]
  command = "pnpm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Functions 配置（内置功能，无需插件）
[functions]
  directory = "netlify/functions"

# 重定向配置
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# OAuth 处理
[[redirects]]
  from = "/oauth/*"
  to = "/.netlify/functions/oauth"
  status = 200