backend:
  name: github
  branch: main # 修改为你的分支名称
  repo: rplstie/Astro-theme-Cactus-zh # 修改为你的 GitHub 仓库路径，格式：用户名/仓库名
  site_domain: mudotarrowmu.netlify.app/admin # 修改为你的 Netlify 域名
  base_url: https://mudotarrowmu.netlify.app/admin # 修改为你的 Netlify URL
  auth_endpoint: oauth # OAuth 认证端点

collections:
  - name: "note"
    label: "笔记"
    folder: "src/content/note"
    create: true
    slug: "{{year}}.{{month}}.{{day}}_{{slug}}"
    fields:
      - { label: "标题", name: "title", widget: "string", required: true }
      - {
          label: "简介",
          name: "description",
          widget: "string",
          default: "这是一篇有意思的文章",
          required: true,
        }
      - {
          label: "发布日期",
          name: "publishDate",
          widget: "datetime",
          date_format: "YYYY-MM-DD",
          time_format: "HH:mm",
          required: true,
        }
      - { label: "正文", name: "body", widget: "markdown" }

  - name: "post"
    label: "博文"
    folder: "src/content/post"
    create: true
    slug: "{{year}}.{{month}}.{{day}}_{{slug}}"
    fields:
      - { label: "标题", name: "title", widget: "string", required: true }
      - {
          label: "简介",
          name: "description",
          widget: "string",
          default: "这是一篇有意思的文章",
          required: true,
        }
      - {
          label: "发布日期",
          name: "publishDate",
          widget: "datetime",
          date_format: "YYYY-MM-DD",
          required: true,
        }
      - { label: "标签", name: "tags", widget: "list", required: true }
      - {
          label: "ogImage",
          name: "ogImage",
          widget: "string",
          default: "/social-card.avif",
          required: true,
        }
      - { label: "正文", name: "body", widget: "markdown" }

media_folder: "public/assets/images" # 文件将被存储在仓库中的位置
public_folder: "/assets/images" # 上传媒体文件的 src 属性

